"""
Module for generating spatial plots of bulk prediction grids, which should
have been generated by eval_grids.bulk_grid_error_stats_to_hdf5
"""
import numpy as np
import pickle as pkl
from datetime import datetime
from pathlib import Path
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D
import cartopy.crs as ccrs
import cartopy.feature as cfeature

from testbed import eval_models
from testbed.plotting import geo_quad_plot,plot_geo_rgb

if __name__=="__main__":
    fig_dir = Path(f"figures/grid_error")
    eval_dir = Path(f"data/pred_grids")
    #eval_dir = Path(f"/rtmp/mdodson/pred_grids")
    ## Load each region's latitude and longitude from a pkl dict, since
    ## the static values aren't stored alongside the gridded predictions
    region_latlons_path = Path("data/static/regional_latlons.pkl")
    region_latlons = pkl.load(region_latlons_path.open("rb"))
    bulk_grids = [
        eval_dir.joinpath("bulk-grid_nc_20180101_20181231_lstm-rsm-9-231.h5"),
        eval_dir.joinpath("bulk-grid_ne_20180101_20181231_lstm-rsm-9-231.h5"),
        eval_dir.joinpath("bulk-grid_nw_20180101_20181231_lstm-rsm-9-231.h5"),
        eval_dir.joinpath("bulk-grid_sc_20180101_20181231_lstm-rsm-9-231.h5"),
        eval_dir.joinpath("bulk-grid_se_20180101_20181231_lstm-rsm-9-231.h5"),
        eval_dir.joinpath("bulk-grid_sw_20180101_20181231_lstm-rsm-9-231.h5"),
        #eval_dir.joinpath("bulk-grid_nc_20180101_20211216_lstm-20-353.h5"),
        #eval_dir.joinpath("bulk-grid_ne_20180101_20211216_lstm-20-353.h5"),
        #eval_dir.joinpath("bulk-grid_nw_20180101_20211216_lstm-20-353.h5"),
        #eval_dir.joinpath("bulk-grid_sc_20180101_20211216_lstm-20-353.h5"),
        #eval_dir.joinpath("bulk-grid_se_20180101_20211216_lstm-20-353.h5"),
        #eval_dir.joinpath("bulk-grid_sw_20180101_20211216_lstm-20-353.h5"),
        ]
    stats_to_plot = [
            "state_error_max",
            #"state_error_mean",
            #"state_error_stdev",
            "state_bias_final",
            "state_nnse",
            "state_kge",
            "res_error_max",
            "res_error_mean",
            "res_nnse",
            "res_kge",
            #"res_error_stdev",
            ]
    feats_to_plot = [
            #"soilm-10",
            #"soilm-40",
            #"soilm-100",
            #"soilm-200",
            "rsm-10",
            "rsm-40",
            "rsm-100",
            ]
    replace_existing = False
    for p in bulk_grids:
        _,region,_,_,model = p.stem.split("_")
        grid_shape,model_config,gen_args,stat_labels = \
                eval_models.parse_bulk_grid_params(p)
        ## Declare a per-timestep generator for the bulk statistics data
        gen = eval_models.gen_bulk_grid_stats(
                bulk_grid_path=p,
                init_time=None,
                final_time=None,
                buf_size_mb=256,
                )
        ## Get indeces for selected data and statistic features
        idxs_feats = tuple([
            gen_args["pred_feats"].index(l)
            for l in feats_to_plot
            ])
        print(stat_labels)
        idxs_stats = tuple([stat_labels.index(l) for l in stats_to_plot])
        ## Get the latlon array of this region from the static dictionary
        latlon = region_latlons[region]
        for stats,idxs,ptime in gen:
            tmp_time = datetime.fromtimestamp(int(ptime)).strftime("%Y%m%d-%H")
            idxs = idxs.astype(int)
            ## declare a 2d array to store the stats to be plotted
            tmp_shape = (
                    *latlon.shape[:2],
                    len(stats_to_plot),
                    len(feats_to_plot)
                    )

            ## subset to only the requested features and statistics
            stats = stats[:,idxs_stats][:,:,idxs_feats]
            ## fill valid pixels with corresponding statistics.
            X = np.full(tmp_shape, np.nan)
            X[idxs[:,0], idxs[:,1]] = stats
            for i in range(len(stats_to_plot)):
                fig_name = f"{stats_to_plot[i].replace('_','-')}_{model}" + \
                        f"_{region}_{tmp_time}.png"
                fig_path = fig_dir.joinpath(fig_name)
                if fig_path.exists() and not replace_existing:
                    continue
                geo_quad_plot(
                        [X[:,:,i,j] for j in range(len(feats_to_plot))],
                        flabels=feats_to_plot,
                        latitude=latlon[...,0],
                        longitude=latlon[...,1],
                        geo_bounds=None,
                        plot_spec={
                            "title":f"{region} {stats_to_plot[i]} {tmp_time}",
                            "cbar_shrink":.8,
                            "text_size":18,
                            "xtick_freq":10,
                            "ytick_freq":5,
                            "idx_ticks":True,
                            "gridlines":True,
                            },
                        show=False,
                        fig_path=fig_path,
                        )
