name: aes
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy=0.22.0
  - curl=7.88.1
  - hdf5=1.12.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - netcdf4=1.6.2
  - numpy=1.23.5
  - opencv=4.7.0
  - pillow=9.4.0
  - pygrib=2.1.4
  - pyhdf=0.10.5
  - pyproj=3.6.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - s3fs=2023.4.0
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - zarr=2.16.1
    #prefix: /home/krttd/.anaconda3/envs/aes
